import "server-only";

import manifestJson from "../../../public/models/manifest.json";
import { STRUCTURE_PLACEMENT } from "@/lib/anatomy/structure-metadata";
import type { Manifest, ManifestEntry } from "@/types/manifest";

/**
 * Server-side access to the structure catalogue.
 *
 * `import "server-only"` is load-bearing: the manifest describes every
 * structure in the app, and importing this from a Client Component would ship
 * the whole catalogue to every visitor. Pages read from here and pass down
 * only the handful of structures the current route actually renders.
 *
 * The split between the two sources is deliberate:
 * - the **manifest** carries geometry metadata (filename, bounding box,
 *   triangle count). It is generated by the asset pipeline and versioned with
 *   the .glb files, so it is always in step with them.
 * - **Supabase** carries curriculum metadata (which structures exist, their
 *   region/group, year level) — the part that changes independently of the
 *   geometry, and that later features like OSPE progress will join against.
 *
 * Until Supabase is configured, the placement map in
 * `lib/anatomy/structure-metadata.ts` stands in for the curriculum half.
 */

const manifest = manifestJson as Manifest;

export interface StructureRecord extends ManifestEntry {
  regionSlug: string;
  groupSlug: string;
  yearLevel: 1 | 2;
}

/** Manifest entries joined with their taxonomy placement. */
function catalogue(): StructureRecord[] {
  return manifest.flatMap((entry) => {
    const placement = STRUCTURE_PLACEMENT[entry.fmaId];
    if (!placement) {
      // A processed model with no placement cannot be reached through the
      // hierarchy, so surface it rather than letting it vanish silently.
      console.warn(
        `[structures] ${entry.fmaId} (${entry.name}) has no entry in STRUCTURE_PLACEMENT and will not appear in any region.`
      );
      return [];
    }
    return [{ ...entry, ...placement }];
  });
}

export function getStructuresInGroup(
  regionSlug: string,
  groupSlug: string
): StructureRecord[] {
  return catalogue()
    .filter(
      (structure) =>
        structure.regionSlug === regionSlug && structure.groupSlug === groupSlug
    )
    .sort((a, b) => a.name.localeCompare(b.name));
}

/** Structure counts keyed by `regionSlug`, for navigation badges. */
export function countsByRegion(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const structure of catalogue()) {
    counts[structure.regionSlug] = (counts[structure.regionSlug] ?? 0) + 1;
  }
  return counts;
}

/** Structure counts keyed by `${regionSlug}/${groupSlug}`. */
export function countsByGroup(): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const structure of catalogue()) {
    const key = `${structure.regionSlug}/${structure.groupSlug}`;
    counts[key] = (counts[key] ?? 0) + 1;
  }
  return counts;
}

export function totalStructureCount(): number {
  return catalogue().length;
}
